module.exports = {
    DEFAULT_CSV_COLUMN_COUNT: 7,
    DEFAULT_CSV_ROW_COUNT: 20,
    DEFAULT_CSV_DELIMETER: ',',
    DEFAULT_SIZE_OF_CHAIN: 5,

    NEW_LINE_DELIMITER: '\n',

    CSV_FILE_SIZE_LIMIT: 1024*10, // 10Kb
    CSV_WORKER_MAX: 7
};